import random

# get the player's name from the user
username = raw_input("Please enter your name: ")
# print the greeting
print ("Hello guessing game player %s.  It's nice to meet you.") % username

# generate a random number for the player to guess
random_number =  random.randrange(1,101)
print ("%s, I'm thinking of a number between 1 and 100.  Try to guess my number.") % username
count = 0
# Set guess to a interger less than the randon number generated by the function
guess = random_number - 1

while guess != random_number:   
#lets get the guess now
    guess = int(raw_input("Your guess? "))
 
    count = count + 1
    if guess < random_number:
        print "Your guess is too low. Try again"

    elif guess > random_number:
        print "Your guess is too high. Try again"

    else:
        print "Well done, %s! You found my number in %d tries" % (username, count)
